// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

int main ()
{
	// for(int i; i < 4000000; i++)

	int i = 1;
	int j = 2;
	int fib = 0; 
	int total = 2;

	while (fib < 4000000)
	{
		fib = i + j;

		i = j;

		j = fib;

		if (fib % 2 == 0)
			total = total + fib;
	}

	std::cout<<total;

	return 0;
}